### ISSUE TITLE
iptables-only image or maintainable way to build custom images

### ISSUE THREAD

**Issue by howardjohn** [GoogleContainerTools/distroless#1333]
Istio currently maintains a small [fork](https://github.com/istio/distroless/tree/iptables/iptables) to build a custom image that is basically base + iptables. 

This is a bit painful, as maintaining a fork is not easy to keep up with and the bazel and .deb fetching experience is rough.

To ease this, it would help to either have:

1. An official `iptables` image, that has exactly the [packages we have](https://github.com/istio/distroless/blob/iptables/iptables/BUILD) and nothing more (I realize this is very demanding/picky, but want to be upfront on what would be required for us to adopt a different image - in particular, there must be no openssl).
2. An easier way to build our own custom images. for example, building the same(ish) image with `apko` is pretty trivial:
```yaml
contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - ca-certificates-bundle
    - glibc
    - iptables
    - wolfi-baselayout
archs:
  - x86_64
  - aarch64
paths:
- path: /run
  type: directory
  permissions: 0o755
accounts:
  users:
    - username: nobody
      uid: 65532
    - username: nobody
      uid: 65534
  run-as: 65532
work-dir: /home/nonroot
```
