### ISSUE TITLE
Add JVM flags support to gcr.io/distroless/java

### ISSUE THREAD

**Issue by reegnz** [GoogleContainerTools/distroless#246]
With the current java image it's not possible to pass JAVA_OPTS.
Being able to pass jvm flags to the process is essential for being able to run java processes correctly in containerized environments:
https://blog.docker.com/2018/04/improved-docker-container-integration-with-java-10/

jvm flags cannot be put after the -jar declaration, as everything behind the jar is interpreted as an application argument.

Therefore the ENTRYPOINT could be changed to support parameterization before the '-jar' part (eg. with env variables).

**Comment by reegnz** [comment]
I read up on it a bit and it turns out you cannot use env variables in the ENTRYPOINT, only in shell form.
But the distroless containers don't contain a shell by default.

It would be desirable to be able to pass jvm args into the container without having to override the entire entrypoint though.

**Comment by coollog** [comment]
Hi @reegnz , JVM args can be set via the `JAVA_TOOL_OPTIONS` environment variable.

For example, with Docker, you would run:

`docker run -e "JAVA_TOOL_OPTIONS=<JVM flags>" <image name>`

And with Kubernetes you would have:

```yaml
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: <name>
    image: <image name>
    env:
    - name: JAVA_TOOL_OPTIONS
      value: <JVM flags>
```
