### ISSUE TITLE
Unable to resolve service name in docker (swarm mode and compose)

### ISSUE THREAD

**Issue by Alvise88** [GoogleContainerTools/distroless#481]
Suppose we have

```Dockerfile
FROM maven:3.6.3-jdk-8-slim as build
WORKDIR /workspace/app

COPY .mvn .mvn
COPY pom.xml .
COPY .git .git
COPY mosaico-app mosaico-app

ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

RUN mvn install -DskipTests
RUN mkdir -p mosaico-app/target/dependency && (cd mosaico-app/target/dependency; jar -xf ../*.jar)

FROM golang:1.14 as golang-build

WORKDIR /go/src/app
COPY cmd cmd

RUN go install -v ./...

FROM gcr.io/distroless/java:8
#FROM adoptopenjdk:8u242-b08-jre-openj9-0.18.1-bionic
COPY --from=golang-build /go/bin/healthcheck /app/healthcheck
HEALTHCHECK --start-period=120s CMD ["/app/healthcheck"]

VOLUME /tmp
ARG DEPENDENCY=/workspace/app/mosaico-app/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app

ENTRYPOINT ["java",  "-cp","app:app/lib/*", "it.myapp.mosaico.BootifulMosaicoApplication"]
```

and compose like 

```yaml
version: '3.7'

services:
  _mosaico:
    image: mosaico/mosaico:latest
  mosaico:
    build: .
    environment:
      - "SPRING_PROFILES_ACTIVE=qa"
    ports:
      - 9006:8080
```

then the mosaico java application (a sidecar) will throw java.net.UnknownHostException: _mosaico.

When i switch back to adoptopenjdk:8u242-b08-jre-openj9-0.18.1-bionic the error goes away.
